# CMake generated Testfile for 
# Source directory: /Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests
# Build directory: /Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/build_host
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(session_lifecycle_test "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/build_host/session_lifecycle_test")
set_tests_properties(session_lifecycle_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;29;add_test;/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;0;")
add_test(localhost_proxy_lease_test "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/build_host/localhost_proxy_lease_test")
set_tests_properties(localhost_proxy_lease_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;30;add_test;/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;0;")
add_test(player_session_test "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/build_host/player_session_test")
set_tests_properties(player_session_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;31;add_test;/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;0;")
add_test(surface_renderer_test "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/build_host/surface_renderer_test")
set_tests_properties(surface_renderer_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;32;add_test;/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;0;")
add_test(event_dispatcher_test "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/build_host/event_dispatcher_test")
set_tests_properties(event_dispatcher_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;33;add_test;/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;0;")
add_test(media_loader_test "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/build_host/media_loader_test")
set_tests_properties(media_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;34;add_test;/Users/yaoshining/Workspaces/MyProjects/copilot-worktrees/VidAll_Player/yaoshining-issue-30-http-arm64-tv-d56122/native/tests/CMakeLists.txt;0;")
